# Generated by Django 6.0.1 on 2026-01-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_list_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='name',
            new_name='category',
        ),
    ]
